const actionsConst = {
  SET_USER: 'SET_USER',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  SET_JWT_TOKEN: 'SET_JWT_TOKEN',
  REMOVE_JWT_TOKEN: 'REMOVE_JWT_TOKEN',
  SET_UPCOMING_ELECTIONS: 'SET_UPCOMING_ELECTIONS',
}

export default actionsConst