const types = {
  SET_USER_INITIAL_STATE: 'SET_USER_INITIAL_STATE',
  SET_USER: 'SET_USER',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  SET_JWT_TOKEN: 'SET_JWT_TOKEN',
  REMOVE_JWT_TOKEN: 'REMOVE_JWT_TOKEN',
  ADD_USER_ELECTION: 'ADD_USER_ELECTION',
  REMOVE_USER_ELECTION: 'REMOVE_USER_ELECTION'
}

export default types